# -*- coding: utf-8 -*-
"""import_lib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13OhoQEAn-PjLU3hTketdHiemw6QmYXK7
"""

import math
import torch
import torch.nn as nn
import torch.nn.functional as F
from datasets import load_dataset
from transformers import AutoModelForCausalLM, AutoTokenizer, get_linear_schedule_with_warmup
import copy
import gc
from tqdm import tqdm
import pandas as pd
import numpy as np
from torch.utils.data import Dataset, DataLoader

def model_size_mb(mdl):
    total = sum(p.numel() * p.element_size() for p in mdl.parameters())
    return total / (1024**2)